version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy

  jenkins:
    image: jenkinsci/blueocean
    environment:
      - VIRTUAL_HOST=jenkins.localhost
      - VIRTUAL_PORT=8080
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    driver: bridge
